# Generated by Django 3.2.19 on 2023-08-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230730_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_room',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('', 'Select an option'), ('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=50),
        ),
    ]
