# Generated by Django 3.2.19 on 2023-07-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qreader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
