# Generated by Django 3.2.19 on 2023-06-23 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('attended_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attended_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.userprofile')),
                ('registered_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='accounts.userprofile')),
            ],
        ),
    ]
