# Generated by Django 3.2.19 on 2023-06-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='phone',
            new_name='qr_code',
        ),
    ]
