# Generated by Django 3.2.19 on 2023-07-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user_type'),
        ('attendance', '0004_alter_attendance_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='registered_by',
        ),
        migrations.AddField(
            model_name='attendance',
            name='registered_by',
            field=models.ManyToManyField(related_name='registration', to='accounts.UserProfile'),
        ),
    ]
